"""This file provides the Task class."""
# Standard package import
from typing import List


class Task:
    """
    This class can be used to model tasks of a scheduling problem.
    Multiple tasks can be used to model jobs of a scheduling problem.

    :param job_index: index of the job to which multiple tasks belong
    :param task_index: index of the task within the job (unique within job and gives order of tasks)
    :param machines: list of machine indices applicable for the specific task (alternatives - pick one)
    :param tools: list of tool indices applicable for the specific task (necessary - pick all)
    :param deadline: time of deadline for the task
    :param instance_hash: Individual hash to represent the instance
    :param done: bool to determine status as done
    :param runtime: time left for the task
    :param started: time the task started at in the schedule
    :param finished: time the task finished at in the schedule
    :param selected_machine: selected machine index from the machines list for the specific schedule
    :param _n_machines: number of all available machines in the scheduling problem instance
    :param _n_tools: number of all available tools in the scheduling problem instance
    :param _feasible_machine_from_instance_init: index of machine in the given instance generated by initial environment
        run to generate deadline time
    :param _feasible_order_index_from_instance_init: index of task in the given instance
        generated by initial environment run to generate deadline time
    # rms: added by me
    :param parentId: id of the parent task
    :param children: list of ids of the children tasks
    :param processing_times: list of processing times for the task on the machines
    :param setup_times: list of setup times for the task on the machines
    :param quantity: quantity of the task
    :param task_type: type of the task:either operation or maintenance
    """
    def __init__(self, job_index: int, task_index: int, machines: List[int] = None,
                 tools: List[int] = None, deadline: int = None, instance_hash: int = None, done: bool = None,
                 runtime: int = None, started: int = None, finished: int = None, selected_machine: int = None,
                 _n_machines: int = None, _n_tools: int = None, _feasible_machine_from_instance_init: int = None,
                 _feasible_order_index_from_instance_init: int = None,
                 parentId: int = None, children: List[int] = None, processing_times: List[int] = None,
                 quantity: int = None, setup_times: List[int] = None, type: str = None):

        # test for correct data type of required and throw type error otherwise
        if not isinstance(job_index, int) or not isinstance(task_index, int):
            raise TypeError("Job index and task index must be of type int.")

        # public - static - required - don't touch after init
        self.job_index = job_index
        self.task_index = task_index

        # public - static - optional - don't touch after init
        self.machines = machines
        self.tools = tools
        self.deadline = deadline
        self.instance_hash = instance_hash

        # public - non-static - optional
        self.done = done
        self.runtime = runtime
        self.started = started
        self.finished = finished
        self.selected_machine = selected_machine

        # protected - optional
        self._n_machines = _n_machines
        self._n_tools = _n_tools
        self._feasible_machine_from_instance_init = _feasible_machine_from_instance_init
        self._feasible_order_index_from_instance_init = _feasible_order_index_from_instance_init

        # protected - non-static - optional
        self.parentId = parentId
        self.children = children
        self.processing_times = processing_times
        self.quantity = quantity
        self.setup_times = setup_times
        self.type = type

    def __str__(self) -> str:
        return f"Task - job index {self.job_index} - task index {self.task_index}"

    def str_info(self) -> str:
        return f"Job index {self.job_index}\nTask index {self.task_index}\nMachines {str(self.machines)}"

    def str_info_more(self) -> str:
        return f"Job index {self.job_index}\nTask index {self.task_index}\nMachines {str(self.machines)}\n Tools {str(self.tools)}\nDeadline {self.deadline}\nInstance hash {self.instance_hash}\nDone {self.done}\nRuntime {self.runtime}\nStarted {self.started}\nFinished {self.finished}\nSelected machine {self.selected_machine}\nNumber of all available machines in the scheduling problem instance {self._n_machines}\nNumber of tools {self._n_tools}\nFeasible machine from instance init {self._feasible_machine_from_instance_init}\nFeasible order index from instance init {self._feasible_order_index_from_instance_init} \nParent id {self.parentId}\nChildren {str(self.children)}\nProcessing times {str(self.processing_times)} \nQuantity {self.quantity} \nSetup times {str(self.setup_times)}"
